name: compsci_ia
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2 # Check for the latest version
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.10+1  # Moved to dependencies section
  firebase_core: ^3.8.0  # Updated to match cloud_firestore's required version
  cloud_firestore: ^5.5.0  # Updated to the latest Firestore version
  firebase_storage: ^12.3.4  # Updated to the latest Firebase Storage version
  firebase_auth: ^5.0.3  # Optional, if you need authentication
  file_picker: ^8.1.4  # To pick files from the device
  intl: ^0.18.0  # Check for the latest version
  pdf: ^3.10.4
  printing: ^5.11.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.11
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
