// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBokgnS6FhPpdO0VMZeIE0h9XWY613YMY4',
    appId: '1:496692803774:web:30a997fbb3e5073cc8c6ef',
    messagingSenderId: '496692803774',
    projectId: 'ibcompsciia-799b8',
    authDomain: 'ibcompsciia-799b8.firebaseapp.com',
    storageBucket: 'ibcompsciia-799b8.appspot.com',
    measurementId: 'G-MSRXWJVM2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYeljNhaJ_FjFeq_pnwLtnhHx9m-k_AcA',
    appId: '1:496692803774:android:afaef94f3ef62478c8c6ef',
    messagingSenderId: '496692803774',
    projectId: 'ibcompsciia-799b8',
    storageBucket: 'ibcompsciia-799b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1VZ5o9h128o5QHNqUwe74teRuEq593e8',
    appId: '1:496692803774:ios:34a21a11695cf322c8c6ef',
    messagingSenderId: '496692803774',
    projectId: 'ibcompsciia-799b8',
    storageBucket: 'ibcompsciia-799b8.appspot.com',
    iosBundleId: 'com.example.compsciIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBokgnS6FhPpdO0VMZeIE0h9XWY613YMY4',
    appId: '1:496692803774:web:df68680f2343514fc8c6ef',
    messagingSenderId: '496692803774',
    projectId: 'ibcompsciia-799b8',
    authDomain: 'ibcompsciia-799b8.firebaseapp.com',
    storageBucket: 'ibcompsciia-799b8.appspot.com',
    measurementId: 'G-1SZ9ZCGYPY',
  );
}
